Develop
sCrypt-Inc/scryptlib pull request #144
Opened 2021-11-04 17:04 UTC by zhfnjust

2021-11-04 22:06 UTC, xhliu requested changes
👍 Looks good overall.

Some minor changes.

2021-11-04 22:06 UTC, xhliu commented on docs/chain_api_zh_CN.md
> +.seal()
//封印交易, 同时自动计算出正确的交易费用和找零余额

2021-11-04 22:06 UTC, xhliu commented on docs/chain_api_zh_CN.md
> +2. 使用 `.setOutput(outputIndex, (tx) => bsv.Transaction.Output)` 添加一个有状态合约的输出。合约新的余额通常需要减去交易费用；
去掉`有状态合约的`

2021-11-04 22:06 UTC, xhliu commented on docs/chain_api_zh_CN.md
> +.addOutput(new bsv.Transaction.Output({ // 添加一个有状态合约的输出, newAmount 是合约新的余额
去掉`有状态合约的`

2021-11-04 22:06 UTC, xhliu commented on README.md
> +## Chain Api
Change `C/chain` to `C/chained` to avoid confusion. Chain usually means blockchain in our context.

2021-11-04 22:06 UTC, xhliu commented on README.md
> +[Chain Api](./docs/chain_api_en.md) makes building transactions more efficient and simple
makes building transactions more efficient and simple
->
makes building transactions easy.

2021-11-04 22:06 UTC, xhliu commented on docs/chain_api_en.md
> +
Have a English draft after u fix cn version. And I will review again.

2021-11-05 01:25 UTC, zhfnjust commented on patches/bsv/lib/errors/spec.js
> +
for add some new Error, like this:

```
{
    name: 'TransactionAlreadySealed',
    message: 'Cannot update sealed transaction'
  }
```

2021-11-05 04:55 UTC, xhliu approved these changes
💯 nice

2021-11-06 00:57 UTC, merged